### PR TITLE
fix( onesync global voices )

### PR DESCRIPTION
**Pull request by izio38**

### CODE REVIEW

**Comment by izio38** [comment]
ooof this is weird.
I Think we need to wait a bit more then

**Comment by SliderKP** [comment]
same problem was solved??

**Comment by HALALsnackbar** [comment]
to add more to my previous comment, even though I restarted the esx_voice resource mid-game, every new player that connected would hear/talk in global proximity.

**Comment by SliderKP** [comment]
i have server with 64 slots i cant solve by this way...

**Pull request closed without merging**
